//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public System.Guid Id { get; set; }
        public string Distrito { get; set; }
        public string Rua { get; set; }
        public string CodigoPostal { get; set; }
        public string CodigoPostalComplemento { get; set; }
        public string NumeroPorta { get; set; }
        public System.Guid PessoaId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
