@startuml
class Categoria {
    + Categoria()
    + Id : Guid <<get>> <<set>>
    + Nome : string? <<get>> <<set>>
    + Descricao : string? <<get>> <<set>>
    + <<virtual>> Produtos : List<Produto> <<get>> <<set>>
}
@enduml
