@startuml
class DetalhesDaVenda {
    + Id : Guid <<get>> <<set>>
    + Seq : int <<get>> <<set>>
    + Produto : Produto? <<get>> <<set>>
    + Quantidade : int <<get>> <<set>>
    + PrecoUnitario : int <<get>> <<set>>
    + TotalDaNota : decimal <<get>> <<set>>
    + DataCriacao : DateTime? <<get>> <<set>>
    + <<virtual>> Venda : Venda? <<get>> <<set>>
}
@enduml
