@startuml
class Estoque {
    + Id : Guid <<get>> <<set>>
    + Quantidade : int <<get>> <<set>>
    + QuantidadeMinima : int <<get>> <<set>>
    + DataModificacao : DateTime? <<get>> <<set>>
    + DataCriacao : DateTime? <<get>> <<set>>
    + <<virtual>> Produto : Produto? <<get>> <<set>>
    + <<virtual>> Loja : Loja? <<get>> <<set>>
}
@enduml
