@startuml
class Loja {
    + Loja()
    + Id : Guid <<get>> <<set>>
    + Nome : string? <<get>> <<set>>
    + Endereco : string? <<get>> <<set>>
    + Ativa : bool? <<get>> <<set>>
    + DataModificacao : DateTime? <<get>> <<set>>
    + DataCriacao : DateTime? <<get>> <<set>>
    + <<virtual>> PontoDeVendas : List<PontoDeVenda> <<get>> <<set>>
    + <<virtual>> Estoques : List<Estoque> <<get>> <<set>>
}
@enduml
