@startuml
class Pagamento {
    + Id : Guid <<get>> <<set>>
    + Seq : string? <<get>> <<set>>
    + ValorPago : decimal <<get>> <<set>>
    + DataCriacao : DateTime? <<get>> <<set>>
    + Loja : Loja? <<get>> <<set>>
    + <<virtual>> TipoPagamento : TipoPagamento? <<get>> <<set>>
}
@enduml
