@startuml
class Venda {
    + Venda()
    + Id : Guid <<get>> <<set>>
    + DataModificacao : DateTime? <<get>> <<set>>
    + DataCriacao : DateTime? <<get>> <<set>>
    + Pago : bool? <<get>> <<set>>
    + Loja : Loja? <<get>> <<set>>
    + <<virtual>> PontoDeVenda : PontoDeVenda? <<get>> <<set>>
    + <<virtual>> DetalhesDasVendas : List<DetalhesDaVenda> <<get>> <<set>>
    + <<virtual>> Utilizador : Utilizador? <<get>> <<set>>
}
@enduml
